language: java
sudo: false
env:
    global:
        #key for github
        #GITHUB_OAUTH_TOKEN
        - secure: "JR4REYxqFYNeqfHXmo3m67FLRpMBUuVqbq5RLo8CoeIcsS5Df1WHDW4uQM6koGHzCuJYdD9C3M6HW4jxSSzOKrHXUT/Nud+1otmzdHIBRjgNHmCc4CNFUShPiDF50CWMYvS0JrzPxOXUSQ0+ZbDXHKpqZXui4V/alJVL22df0XEJ3se5GSCzs7SbzZKsduxNYVpQcHwTVJs8qNj4xBWgRTXyRfzbj4cM7Qly6BvwZa+GBzaX49G9GZfqPsSzuSCYwA59XnbltjaIG2p3rPQN9NmldIQP+L6s1VMddmJrnUqrV7o93vzuIrLTHUQO+H9iENaW2fLunmxl7PhKLVdLwKBuhOcPrHPh0ykWtfXRHeL8f1NIQbtl9jEvykA2JqdQ32QhyrWI4h1BY7Hc0zch4aoah1bWAju74c5QQ176hOxcAFk3oUXmLKLsOkbePNCzUCid9vmTosMwIv6Z4FhpJ6jzFzA8kNLM+nPOUghCE534P2OfjSfpMCKrWnkk96M2O+fLPyurdwLCxhT/3uX1a/LOFGKbwYl6qp8Jb2PYIbRHFf/Ldo6c/AVnMhl042tRs/HkNLukbNurY+yNP5sCiJzKITdFRiP/8zl2xcn4T0oK5bGD6+szyFOFpf/noGFwqDe7SJL/7sHCeDPep82nBHA7rzHvr2ods5a5n70gMl4="
        - environment=test
        #sonatype credentials
        #OSSRH_JIRA_USERNAME
        - secure: "BcGQ0Ct6zHekeDGONNwovav8NM+Q6XnC/HgUhnVm0GFq5aMfAdBzSjzPDtr9y+PEJEQhRdPcNOu965va76crE5quWGPEPExKTF11dIqcUFR2mmRaUkdxQECbLwfrP/FQHv6dcL+jbs98CVPzE1Vywrn01WF2GT8OHSdE+cwEENxhGXZKQaToXl+BALREiSI1j+YSSB/YicDQ70nzWJN7BMjc2p/eQCE6+KSCFRHFMfyEGic7HWHnjH8QUXyn/SG7wKbjratLeicZxTvtKwKuyI4B6G0QoeWRAymePgYmn0dDV5knO3xH2Ket/SqRY8QIXH7fTyD19xurf39vp1V5xnVQ78u2vyZsebjhyFrTi7iB5mR8hq0ruyE9Ang+F6CctKtDLwQuGi/VGMap2oCi5/S8I/Il2uQWFB0XJQTvMCMDAwHdfwiS6YnkAJJS1vA18ezeo6QTZAaGhA8tXZ3mh1J6mcaKherFzihKz/Zw8EwogrCcWTjVECZiVhCxV93byx9j8qq/EcUDGqFd3OkmoAk2tHuvNG0CW5YVlZ3xl0eNPuCdBXo+rAqiU8iFmSi6KIMOLFW95S+5I6OVcGJ8drv8w5kQj/15GztlNGc8mHLChjjkAlh/6CSRmpaO5gF1zah1ODCDlh+gLoSAn1rhrVVAyHydM6iEx6a8atXjLQw="
        #OSSRH_JIRA_PASSWORD
        - secure: "d6NocKVELYfh7/IljpSRmklA02cqGgdhBS/acIiRWxmkEuP2qmtZFuDxXUOFbRhVtQoxCvhQy9liLiHwE5CQYckR8nVxm1zqHEpUY9wcwA9wwY5K1cKD69WQRH0M4J0i+wRHurLkGboN92D6mc+vMCHpCMkAQ8ggckT8TSHUptilcjIcwK3mIjke0Wn0R3aNFJvTztLGmopvl/45py2bmFrqfrvzhsdyBM2/ge7earj2m9FF98/TKkR9ONHgM2llty+GrF0HqUy+8oxaO8bwaiw7yWoSUjtdo/eGKLg/1LaMulhZet5Rc2VqwxLefI8HAkAVpLyPstu0zxeOH/xJMBZNdVp/CR1Bjp8PWnYb7ejDGSVuIZd4PQExWWqadEXKzjpL1YI6nqbBpobwOG9soNTpl6S91ao4tS8EYzzU2P1veDRruVWWz5jrtxDgzdjPfhXjkAm+QzDUoIlynNm14r9LAkqoMzZSwDc/rmCItq5KVOcsP6Duy1nOTuz5WTJCXisGmbKRzyrYN7WuKjSA96OozrXE4UUGKs3JbvhfL/DUBP95w9+pcRI2qRZI5t+s1opOi745lWlH8n53PnJfDTivo3XVk124uoUEpLoGNY3U79qZYgVduRs9Ywsa7jvCMMWyi0za79yfuDtNU0pS81I/+sZIe7BBUuSJ7N7LuYM="
        #signing key
        #GPG_KEY_NAME
        - secure: "S6dRmGc/y2BdOIlnSsauNKr0NkJEqolq6TEKeHXJMad7Dahjd4vJB8nYlAil0EX+pVwz64FwxeFW7PoeHPGiEn1+fEkvjfAuqcfsq19x5MJkB1ToUw4Q8RMkqIYsymyY9+lpSPfs3LoputzDLD9ikKdl7cfQCqFWt4VOzbqUPvPiX7S2GsI2EVCMl3KeT0otmErCBLP4PLyBydFkj49GCMeyoYYlRpyxkHB8ifgo+ucoyz1KS+1cOECPnyGHsk58ny+erdb+JiHmFU1xMPH8ZbRuocpvHmZvmP56rx3WzgsR4HEWF3Azhnl3HByorHI/rHn2FJC4grcI630gOVrIJVt6CPP5HRtrE1MsihWOM6gW9IcLZU8Jeo/j4YUnLcnrEE1Suf6ahmnaRw0QeG1l7sl/9CWV5G0Aia6zjIISuQFfNaWoeR5m1JaCWNMpFv8SJozn4PnIe0qrXs7U2XgeJD3eNBfLjAC0ws48lNfgf39qoPopRZeqgoqBrIoJkfkQtNLe963uWcCSKcExMZ+ikavnjJ1fdRmaw/1ysy+HzCNtRwDYTmUUOExbG0ZwOXvOPTmcnCMUdCwMKFwnvrEJYCa95L2ujvvxW8Wfif5fyHt66M11/89sVdkIZTcMRNcf+6LrXCHf0jOzLwmOGqcEyJIF5T1eGvHeUtOMKnPOuiU="
        #GPG_PASSPHRASE
        - secure: "hiEAdBKtK49VarzQb11+Pt05dSlFqk7RMxgUBI9Q1bpZXH8K7eX4DelvJ0W6Gt7MTQi+okMJkSi/JJ0/7Xer/GQa+I6mpQTb6HFdaGnmTS4KQQGjL2Cesj9L3H9CzWVAaMzM1HzYvvWAPDwoWGUjzc/0tMQyad55gKHXl2BcY3XzUMRukXdGxoRnSO2WTfcVjTDBemU+iV82W5KLKyLXNCNsm8/2icjOPgAd8i8Vs+ovDE2QkETOZItPAdpGFqOG2n3fm6C+Tt+/H/GmuybNBDsoQcOvjNpaPLoOFNd0WOKioLBrVSq9/bsNqPoGbXcyE3ueYw/a7led8SuNHVeqh5BWkSvEQde/v/zNiPqs/rA40pOWC45AAw13tyaJtLP1joP0LSBOB0DGkaHPPHZgfpY/5zsO5NYBM/EcWequmj6+amN7qw9LDT0Hppho7zGCoGlwMXGMSx/lmZuq7mgZOMdX6+ActoF3/U7Sb+ef4I4MtKbvCyACX+Y+AA7qx2E7mvJNOr9Uin6QHOARs8F7KCxq4W4El6yOXPE3hjvcE1Pc+p9/0JbovAV2RspDDuV82qQdMh9pgvEW0eQFDEM/ZBlN7JiXcV3Mn+nivhfX4Hn0nVCe3UkslWKHA4ZqiGYtkx/TjG0QjBOFBgsKRATsjfL379Wc98rvW3x6ZqrwwI8="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "OIK7UXRFf3JbCef/uacV/w6L4AvFrkXinG1IVoPIERiyVb5lVp8ZOU1Fe1YBiKNicD+Xe3aW7MZ+7tgWqXccT85oAY3Aqfz4/V1WXPUIkkFdqhOdbnvt2CWbK8r4YI8qiZemVuHKLY0uYlBEhPF0ieR4vwDg87Q+N2bUwwbJiu26ZYy1tHxH7ErXyaMIwKTPO5sQ3bXQ9Gn++JrSigI+HvD0t6BGhsxTj8NCrSZruazghIhJiV69jdjy3MLiym2USGq66Zby461NXm+V5EAZZKVRSFTD/hqy9e5fKQLQPYetRnthirLnoPDzRmZw4LL9QpzuB/Vqm148UYKmuE69dmdJG+f72EQ7yxFRgDRDOvCL3NOnXmEALpeTN7wh8x078OLl9jELRbxXwXO77niHyoeJVE2GDaQ+ZtHW1NUdZkCJmipB8zs+7rWH0EY9Mgrl499lJwUrjlS3eeNQPBZ1gB34MVIDS3B9YcC7GEysuJk0sRQ2GSVixOeko0pgGlMDOV5CJ8YwDovd4MfwF5ig0r1McK64s4yJhXePe/erpzCziSWjn7AUk/gGzbDnLMQVqxAXXIaaakjvOIzoWmhuN4zm7nQgzjqlR+tpooCnJ4Rw5aUm7J8taOKsGLTvyZEcJddmWNlaT1zpgiZHt0YrQvkw2xJFKBHpqkc2o/A8ZRc="

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
- travis_wait 40 mvn clean jacoco:prepare-agent install jacoco:report coveralls:report site -Denvironment=test -P !build-extras
- sonar-scanner

cache:
  directories:
  - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: master

after_success:
- ./cd/before-deploy.sh
- ./cd/deploy.sh
