= Reference
:description: Generated project reports and the bibliography behind the matrix decomposition and norm estimation algorithms.

These reports are generated during the Maven build and site lifecycle.

== Generated Reports

[cols="1,3",options="header"]
|===
|Report
|Description

|https://albertoirurueta.github.io/irurueta-algebra/mvn-site/apidocs/com/irurueta/algebra/package-summary.html[Javadoc]
|API reference generated by the Maven Javadoc plugin as part of the Maven site.

|https://albertoirurueta.github.io/irurueta-algebra/mvn-site/jacoco/index.html[JaCoCo]
|Code coverage report generated during Maven execution.

|https://albertoirurueta.github.io/irurueta-algebra/mvn-site/surefire.html[Surefire]
|Unit test execution report generated by the Maven Surefire reporting tools.

|https://sonarcloud.io/project/overview?id=albertoirurueta_algebra[SonarCloud]
|Project quality dashboard with issue analysis, code quality information, and coverage metrics.

|https://github.com/albertoirurueta/irurueta-algebra[GitHub repository]
|Source code repository for the project.
|===

== Bibliography

Most of the matrix decomposition algorithms implemented by this library follow the descriptions
and reference C++ implementations given in Chapter 2, "Solution of Linear Algebraic Equations", of
_Numerical Recipes: The Art of Scientific Computing_, 3rd Edition (Cambridge University Press,
2007). `RQDecomposer` and the norm estimation classes are instead based on the external references
listed below. The table maps each class to the section or page it is based on.

[cols="1,2,1",options="header"]
|===
|Class
|Reference
|Section / pages

|xref:gauss-jordan-elimination.adoc[`GaussJordanElimination`]
|Numerical Recipes, 3rd Edition
|2.1 "Gauss-Jordan Elimination", pp. 41-46

|xref:lu-decomposition.adoc[`LUDecomposer`]
|Numerical Recipes, 3rd Edition
|2.3 "LU Decomposition and Its Applications", pp. 48-56

|xref:singular-value-decomposition.adoc[`SingularValueDecomposer`]
|Numerical Recipes, 3rd Edition
|2.6 "Singular Value Decomposition", pp. 65-75

|xref:cholesky-decomposition.adoc[`CholeskyDecomposer`]
|Numerical Recipes, 3rd Edition
|2.9 "Cholesky Decomposition", pp. 100-102

|xref:qr-decomposition.adoc[`QRDecomposer`] / xref:economy-qr-decomposition.adoc[`EconomyQRDecomposer`]
|Numerical Recipes, 3rd Edition
|2.10 "QR Decomposition", pp. 102-106

|xref:economy-qr-decomposition.adoc[`EconomyQRDecomposer`]
|Wikipedia, "QR decomposition"
|https://en.wikipedia.org/wiki/QR_decomposition

|xref:rq-decomposition.adoc[`RQDecomposer`]
|Mathematics Stack Exchange, "RQ decomposition"
|https://math.stackexchange.com/questions/1640695/rq-decomposition

|xref:frobenius-norm.adoc[`FrobeniusNormComputer`]
|Wikipedia, "Matrix norm"
|https://en.wikipedia.org/wiki/Matrix_norm

|xref:one-norm.adoc[`OneNormComputer`] / xref:infinity-norm.adoc[`InfinityNormComputer`]
|Wikipedia, "Norm (mathematics)"
|https://en.wikipedia.org/wiki/Norm_(mathematics)#Maximum_norm_(special_case_of:_infinity_norm,_uniform_norm,_or_supremum_norm)
|===

=== Cited references

Numerical Recipes' own chapter 2 points to these works for a deeper treatment of linear algebra,
and they are also cited directly in this library's class-level Javadoc:

* Golub, G.H., and Van Loan, C.F. 1996, _Matrix Computations_, 3rd ed. (Baltimore: Johns Hopkins
  University Press).
* Wilkinson, J.H., and Reinsch, C. 1971, _Linear Algebra_, vol. II of _Handbook for Automatic
  Computation_ (New York: Springer).
* Wilkinson, J.H. 1965, _The Algebraic Eigenvalue Problem_ (New York: Oxford University Press).
* Forsythe, G.E., and Moler, C.B. 1967, _Computer Solution of Linear Algebraic Systems_ (Englewood
  Cliffs, NJ: Prentice-Hall).
* Forsythe, G.E., Malcolm, M.A., and Moler, C.B. 1977, _Computer Methods for Mathematical
  Computations_ (Englewood Cliffs, NJ: Prentice-Hall).
* Anderson, E., et al. 1999, _LAPACK User's Guide_, 3rd ed. (Philadelphia: S.I.A.M.). Online with
  software at http://www.netlib.org/lapack.
* Press, W.H., Teukolsky, S.A., Vetterling, W.T., and Flannery, B.P. 2007, _Numerical Recipes: The
  Art of Scientific Computing_, 3rd ed. (Cambridge, UK: Cambridge University Press), Chapter 2,
  "Solution of Linear Algebraic Equations", pp. 37-109.
* Wikipedia contributors, "QR decomposition", _Wikipedia, The Free Encyclopedia_,
  https://en.wikipedia.org/wiki/QR_decomposition.
* Wikipedia contributors, "Matrix norm", _Wikipedia, The Free Encyclopedia_,
  https://en.wikipedia.org/wiki/Matrix_norm.
* Wikipedia contributors, "Norm (mathematics)", _Wikipedia, The Free Encyclopedia_,
  https://en.wikipedia.org/wiki/Norm_(mathematics).
* Mathematics Stack Exchange contributors, "RQ decomposition",
  https://math.stackexchange.com/questions/1640695/rq-decomposition.
